name: Push kernel changes to BlueOS
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: blueos-push-${{ github.repository }}
  cancel-in-progress: false
jobs:
  push:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos-lab/josh-sync/.github/workflows/blueos-push.yml@2ab89e88372723d15218f4ebc3a2634701c0d03a
    with:
      github-app-client-id: ${{ vars.JOSH_SYNC_APP_CLIENT_ID }}
      josh-sync-repository: vivoblueos-lab/josh-sync
      josh-sync-revision: 2ab89e88372723d15218f4ebc3a2634701c0d03a
    secrets:
      github-app-secret: ${{ secrets.JOSH_SYNC_APP_PRIVATE_KEY }}
